BLACK = (0, 0, 0, 1)
WHITE = (1, 1, 1, 1)
BLACK_05 = (0, 0, 0, 0.5)
WHITE_05 = (1, 1, 1, 0.5)
RED_05 = (1, 0, 0, 0.5)
ORANGE_05 = (1, 0.5, 0, 0.5)
FILE_NAME = 'files/my_file.txt'
VIEW = 'q'
TERN_RIGHT = 'r'
TERN_LEFT = 'l'
K_LEFT = 'w'
K_RIGHT = 's'
K_FORWARD = 'd'
K_BACK = 'a'
KEY_UP = 'u'
KEY_DOWN = 'y'
K_MODE = 'z'
K_REMOVE = 'g'
K_ADD = 'f'
K_SAVE = 'control-s'
K_NEW = 'control-n'